//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISComponents.ReportGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSISComponents.ReportGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        internal static string An_unknown_error_has_occurred_ {
            get {
                return ResourceManager.GetString("An_unknown_error_has_occurred_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap codeplex {
            get {
                object obj = ResourceManager.GetObject("codeplex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GitHub {
            get {
                object obj = ResourceManager.GetObject("GitHub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oh22is {
            get {
                object obj = ResourceManager.GetObject("oh22is", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define a ReportServer.
        /// </summary>
        internal static string Please_define_a_ReportServer {
            get {
                return ResourceManager.GetString("Please_define_a_ReportServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a password and/or username..
        /// </summary>
        internal static string Please_provide_a_password_and_or_username_ {
            get {
                return ResourceManager.GetString("Please_provide_a_password_and_or_username_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Report..
        /// </summary>
        internal static string Please_select_a_Report_ {
            get {
                return ResourceManager.GetString("Please_select_a_Report_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportGeneratorTask {
            get {
                object obj = ResourceManager.GetObject("ReportGeneratorTask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportGeneratorTask.
        /// </summary>
        internal static string ReportGeneratorTask_ {
            get {
                return ResourceManager.GetString("ReportGeneratorTask_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportGeneratorTask_Banner {
            get {
                object obj = ResourceManager.GetObject("ReportGeneratorTask_Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportserver:.
        /// </summary>
        internal static string Reportserver_ {
            get {
                return ResourceManager.GetString("Reportserver_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report server could not be reached. Exception: .
        /// </summary>
        internal static string The_report_server_could_not_be_reached__Exception__ {
            get {
                return ResourceManager.GetString("The_report_server_could_not_be_reached__Exception__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report snapsoht could not been created..
        /// </summary>
        internal static string The_report_snapsoht_could_not_been_created_ {
            get {
                return ResourceManager.GetString("The_report_snapsoht_could_not_been_created_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified report folder does not exist..
        /// </summary>
        internal static string The_specified_report_folder_does_not_exist_ {
            get {
                return ResourceManager.GetString("The_specified_report_folder_does_not_exist_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no filename specified..
        /// </summary>
        internal static string There_was_no_filename_specified_ {
            get {
                return ResourceManager.GetString("There_was_no_filename_specified_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable:.
        /// </summary>
        internal static string Variable_ {
            get {
                return ResourceManager.GetString("Variable_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you retrieve the report parameter, an error has occurred: .
        /// </summary>
        internal static string When_you_retrieve_the_report_parameter__an_error_has_occurred__ {
            get {
                return ResourceManager.GetString("When_you_retrieve_the_report_parameter__an_error_has_occurred__", resourceCulture);
            }
        }
    }
}
