//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISComponents.ReportGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/ReportServer_SQL2K8/ReportExecution2005.asmx")]
        public string SSISComponents_SQLServer_ReportGeneratorTask_ReportExecution2005_ReportExecutionService {
            get {
                return ((string)(this["SSISComponents_SQLServer_ReportGeneratorTask_ReportExecution2005_ReportExecutionS" +
                    "ervice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sp01/_vti_bin/ReportServer/ReportService2010.asmx")]
        public string SSISComponents_DTS_Tasks_ReportGeneratorTask_SharePoint_ReportingService2010 {
            get {
                return ((string)(this["SSISComponents_DTS_Tasks_ReportGeneratorTask_SharePoint_ReportingService2010"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://NOTEBOOK-TE:80/ReportServer_SQL2K8/ReportExecution2005.asmx")]
        public string datenfabrik_SQLServer_ReportGeneratorTask_ReportExecution2005_ReportExecutionService {
            get {
                return ((string)(this["datenfabrik_SQLServer_ReportGeneratorTask_ReportExecution2005_ReportExecutionServ" +
                    "ice"]));
            }
        }
    }
}
